### ISSUE TITLE
Exception using BigQueryIO

### ISSUE THREAD

**Issue by sparkofreason** [atdixon/thurber#10]
This is a longshot, not sure this issue has anything to do with thurber, but it seems rare via Google. Seeing sporadic exceptions like this writing to BigQuery:

```
May 21, 2021 5:04:10 PM io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference cleanQueue
SEVERE: *~*~*~ Channel ManagedChannelImpl{logId=9, target=bigquerystorage.googleapis.com:443} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
	at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:93)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:53)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:44)
	at io.grpc.internal.ManagedChannelImplBuilder.build(ManagedChannelImplBuilder.java:612)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:261)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:327)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.access$1700(InstantiatingGrpcChannelProvider.java:74)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider$1.createSingleChannel(InstantiatingGrpcChannelProvider.java:220)
	at com.google.api.gax.grpc.ChannelPool.create(ChannelPool.java:72)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:227)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:210)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:169)
	at com.google.cloud.bigquery.storage.v1beta2.stub.GrpcBigQueryWriteStub.create(GrpcBigQueryWriteStub.java:138)
```

There's a lot more stack trace. I'm on the latest versions of thurber and the Beam SDK's.  I'm not even sure this is actually a problem, because the pipeline keeps running, but not clear whether it's dropping data due to this. Seen both using direct runner and Dataflow runner. I don't suppose this rings a bell?

I'll also try to put together a minimal example.

Tangent: is there a better place to discuss thurber without filing an issue here? Thanks.

**Comment by sparkofreason** [comment]
I changed the versions of the Beam libs to match what thurber was using, and the problem seems to have gone away.

**Comment by atdixon** [comment]
Ah okay - good to have this on my radar when I can upgrade & test thurber
with `2.29.0` or later.
